build pkcs11-provider only
error: failed to select a version for `cryptoki`.
    ... required by package `parsec-service v0.7.2 (/home/victor.chong/work/swg/build/qemu/out-br/build/parsec-service-0.72)`

Signed-off-by: Victor Chong <victor.chong@linaro.org>